import Spline from "@splinetool/react-spline";
import dayjs from "dayjs";
import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import { useCallback } from "react";
import { useInterval, useLocalStorage, useUpdate } from "react-use";

import { api } from "~/utils/api";

const useToggleLocalStorage = (key: string, initialValue: boolean) => {
  const [value, setValue] = useLocalStorage(key, initialValue);
  const toggle = useCallback(
    (value: boolean | undefined) =>
      setValue((v) => (typeof value === "boolean" ? value : !v)),
    []
  );
  return [value, toggle];
};

const Time = () => {
  const update = useUpdate();

  useInterval(update, 1000);

  return <span className="time">{dayjs().format("HH:mm:ss")}</span>;
};

const Date = () => {
  const update = useUpdate();
  const [show, toggle] = useToggleLocalStorage("show-date", true);

  useInterval(update, 1000);

  return (
    <span
      className="date"
      style={{ opacity: show ? 1 : 0 }}
      onClick={(e) => {
        e.stopPropagation();
        e.preventDefault();
      }}
    >
      {dayjs().format("ddd DD")}
    </span>
  );
};

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Oppo Concept Design: Oppogochi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="oppo-phone" id="oppo-phone">
            <Image
              src="/oppo-flip-phone-outline.png"
              alt={"oppo flip phone outline"}
              width={1000}
              height={1200}
            />
            <div className="spline-container">
              <Date />
              <Time />
              <Spline
                className=""
                scene="https://prod.spline.design/UDDHjzjeH77xCSwy/scene.splinecode"
              ></Spline>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
